-- Purpose: remove legacy users/courses tables and rebuild recommendations for Mautic lead-based data.
-- WARNING: destructive migration. Existing data in recommendations, users, and courses will be removed.
--
-- Up
DROP TABLE IF EXISTS recommendations;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS courses;

DROP TYPE IF EXISTS recommendationtype;

CREATE TYPE recommendationtype AS ENUM ('recommendation', 'article');

CREATE TABLE recommendations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type recommendationtype NOT NULL,
    lead_id INTEGER NOT NULL,
    text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_recommendations_lead_id ON recommendations (lead_id);

-- Down (rollback)
DROP TABLE IF EXISTS recommendations;
DROP TYPE IF EXISTS recommendationtype;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(150) NOT NULL UNIQUE,
    digital_footprints TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_users_login ON users (login);

CREATE TABLE courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT NOT NULL
);

CREATE INDEX ix_courses_name ON courses (name);

CREATE TABLE recommendations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    text VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_recommendations_user_id ON recommendations (user_id);
