-- Purpose: replace legacy recommendation enum schema with normalized resource/recommendation type dictionaries.
-- WARNING: destructive migration. Existing data in recommendations will be removed.
--
-- Up
DROP TABLE IF EXISTS rag_resources;
DROP TABLE IF EXISTS resource_types;
DROP TABLE IF EXISTS recommendations;
DROP TABLE IF EXISTS recommendation_types;

DROP TYPE IF EXISTS recommendationtype;

CREATE TABLE resource_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE rag_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR(2048),
    type_id INTEGER NOT NULL REFERENCES resource_types(id),
    title VARCHAR(500),
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_rag_resources_type_id ON rag_resources (type_id);

CREATE TABLE recommendation_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id BIGINT NOT NULL,
    type_id BIGINT NOT NULL REFERENCES recommendation_types(id),
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_recommendations_lead_id ON recommendations (lead_id);

-- Down (rollback)
DROP TABLE IF EXISTS rag_resources;
DROP TABLE IF EXISTS resource_types;
DROP TABLE IF EXISTS recommendations;
DROP TABLE IF EXISTS recommendation_types;

CREATE TYPE recommendationtype AS ENUM ('recommendation', 'article');

CREATE TABLE recommendations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type recommendationtype NOT NULL,
    lead_id INTEGER NOT NULL,
    text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_recommendations_lead_id ON recommendations (lead_id);
